export const newBrandColors = {
  beige: '#FDF9E9',
  brightGreen: '#81F494',
  darkGreen: '#0B4938',
  lightBlue: '#80B7F4',
  darkBlue: '#093D77',
  charcoal: '#283131',
  orange: '#FE9F1C',
  lightRed: '#FAC2C2',
  deepRed: '#B3063E',
};

export const lightTheme = {
  body: newBrandColors.beige,
  text: newBrandColors.charcoal,
  toggleBorder: newBrandColors.lightBlue,
  background: newBrandColors.beige,
  sidebarBackground: '#FFFFFF',
  sidebarText: newBrandColors.charcoal,
  sidebarHighlight: newBrandColors.lightBlue + '30', // 30% opacity
  mainContentBackground: '#FFFFFF',
  cardBackground: '#FFFFFF',
  borderColor: newBrandColors.lightBlue + '50', // 50% opacity
  accentColor: newBrandColors.darkBlue,
  accentColorObjective: newBrandColors.darkGreen,
  accentColorTool: newBrandColors.darkBlue,
  filterChipBackground: newBrandColors.lightBlue + '30',
  filterChipText: newBrandColors.darkBlue,
  filterChipRemoveBackground: newBrandColors.lightRed,
  buttonBackground: newBrandColors.darkGreen,
  buttonText: newBrandColors.beige,
  buttonHover: newBrandColors.brightGreen,
  clearButtonBackground: 'transparent',
  clearButtonText: newBrandColors.charcoal,
  clearButtonHoverBackground: newBrandColors.lightBlue + '20',
  searchInputBackground: '#FFF',
  searchInputText: newBrandColors.charcoal,
  searchInputBorder: newBrandColors.lightBlue,
  primaryGradient: `linear-gradient(135deg, ${newBrandColors.darkGreen} 0%, ${newBrandColors.darkBlue} 100%)`,
  secondaryGradient: `linear-gradient(135deg, ${newBrandColors.lightBlue} 0%, ${newBrandColors.brightGreen} 100%)`,
  warningColor: newBrandColors.orange,
  errorColor: newBrandColors.deepRed,
  successColor: newBrandColors.brightGreen,
};

export const darkTheme = {
  body: newBrandColors.charcoal,
  text: newBrandColors.beige,
  toggleBorder: newBrandColors.lightBlue,
  background: newBrandColors.charcoal,
  sidebarBackground: '#1A1A1A',
  sidebarText: newBrandColors.beige,
  sidebarHighlight: newBrandColors.darkGreen + '50',
  mainContentBackground: '#1A1A1A',
  cardBackground: '#2A2A2A',
  borderColor: newBrandColors.lightBlue + '30',
  accentColor: newBrandColors.lightBlue,
  accentColorObjective: newBrandColors.brightGreen,
  accentColorTool: newBrandColors.lightBlue,
  filterChipBackground: newBrandColors.darkGreen + '80',
  filterChipText: newBrandColors.beige,
  filterChipRemoveBackground: newBrandColors.deepRed,
  buttonBackground: newBrandColors.darkGreen,
  buttonText: newBrandColors.beige,
  buttonHover: newBrandColors.brightGreen,
  clearButtonBackground: 'transparent',
  clearButtonText: newBrandColors.beige,
  clearButtonHoverBackground: newBrandColors.darkGreen + '30',
  searchInputBackground: '#2A2A2A',
  searchInputText: newBrandColors.beige,
  searchInputBorder: newBrandColors.lightBlue,
  primaryGradient: `linear-gradient(135deg, ${newBrandColors.darkGreen} 0%, ${newBrandColors.darkBlue} 100%)`,
  secondaryGradient: `linear-gradient(135deg, ${newBrandColors.lightBlue} 0%, ${newBrandColors.brightGreen} 100%)`,
  warningColor: newBrandColors.orange,
  errorColor: newBrandColors.lightRed,
  successColor: newBrandColors.brightGreen,
};

export type ThemeType = typeof lightTheme; 